In [74]:
def calcDistFromAns(matrix, n):
  total = 0
  for i in range(n):
    for j in range(n):
      if(matrix[i][j] == 0):
        x = n-1
        y = n-1
      else:
        x = int(matrix[i][j]/n)
        y = matrix[i][j]%n - 1
        if(y<0):
          y+=n
          x-=1
      diff = abs(x - i) + abs(y - j)
      total += diff
  return total

In [75]:
import random

def generateRandomMatrix(n = 5):
  dic = dict()
  nums = []

  for i in range(1,n*n):
    nums.append(i)

  matrix = []

  for i in range(n):
    temp = []
    for j in range(n):
      if(len(nums) == 0):
        temp.append(0)
        break
      index = random.randint(0, len(nums)-1)
      temp.append(nums[index])
      nums.pop(index)
    matrix.append(temp)
  dic[0] = matrix
  dic[1] = [n-1,n-1]
  dic[2] = calcDistFromAns(matrix, n)
  dic[3] = []
  dic[4] = 0
  if(not IsSolvable(dic)):
    temp = dic[0][n-1][n-3]
    dic[0][n-1][n-3] = dic[0][n-1][n-2]
    dic[0][n-1][n-2] = temp
  return dic


In [76]:
def checkInside(n, i, j):
  if(i<0 or i>=n or j <0 or j>=n):
    return False
  return True

In [77]:
def isAnswer(matrix, n):
  start = 0
  for i in range(n):
    for j in range(n):
      if(matrix[i][j] != start):
        return False
      start += 1
  return True

In [78]:
def compare2DArrays(arr1, arr2):
  for i in range(len(arr1)):
    for j in range(len(arr1[0])):
      if(arr1[i][j] != arr2[i][j]):
        return False
  return True

In [79]:
def checkIfNotVisisted(completedArray, dic):
  for i in range(len(completedArray)):
    if(compare2DArrays(completedArray[i][0], dic[0])):
      # if(completedArray[i][3] > dic[3]):

      return False
  return True

In [103]:
def addNode(q, newNode):
  leastIndex = 0
  start = 0
  end = len(q) - 1
  # print(newNode[2], newNode[3])
  # reqNum = newNode[2] + newNode[4]
  reqNum = newNode[2]
  index = int((start+end)/2)
  while(end - start >= 0):
    # print(start, index, end)
    index = int((start+end)/2)
    qstrt = q[start][2]
    qend = q[end][2]
    if(end-start ==0):
      if(qstrt < reqNum):
        q.append(newNode)
        return
      elif(qstrt > reqNum):
        q.insert(start, newNode)
        return
    if(end - start == 1):
      if(qstrt >= reqNum):
        q.insert(start, newNode)
        return
      if(end >= reqNum):
        q.insert(start+1, newNode)
        return
      if(end < reqNum):
        q.insert(start + 2, newNode)
        return
    midValue = q[index][2]
    if(midValue > reqNum):
      end = index
    elif(midValue < reqNum):
      start = index
    else:
      break
  q.insert(index, newNode)

In [104]:
arr = {0: [[1, 4, 2], [7, 6, 5], [3, 8, 0]], 1: [2, 2], 2: 10, 3: [], 4: 0}
q = [{2:6, 4:4},{2:10,4:0}]
addNode(q,arr)
print(q)

[{2: 6, 4: 4}, {2: 10, 4: 0}, {0: [[1, 4, 2], [7, 6, 5], [3, 8, 0]], 1: [2, 2], 2: 10, 3: [], 4: 0}]


In [81]:
def getInvCount(matrix):
    N = len(matrix)
    M = len(matrix[0])
    arr1=[]
    for y in matrix:
        for x in y:
            arr1.append(x)
    arr=arr1
    inv_count = 0
    for i in range(N * M - 1):
        for j in range(i + 1,N * M):
            if (arr[j] and arr[i] and arr[i] > arr[j]):
                inv_count+=1
    return inv_count

In [82]:
def IsSolvable(item):
  matrix = item[0]
  blank = item[1]
  i = blank[0]
  j = blank[1]
  no_of_inv = getInvCount(matrix)
  if(len(matrix) % 2 == 1):
    if(no_of_inv % 2 == 0):
      return True
  else:
    if((len(matrix) - i)%2 == 0):
      if(no_of_inv%2 == 1):
        return True
    else:
      if(no_of_inv%2 == 0):
        return True
  return False

In [105]:
import copy

n=3
arr = generateRandomMatrix(n)
print(arr)
IsSolvable(arr)

q = []
q.append(arr)
route = []

completedArray = []
x = 0
move = [[-1,0], [0,-1], [1,0], [0,1]]
while(len(q) != 0):
  print("nodes visited:",x)
  x+=1
  p = q[0]
  q.pop(0)
  # print(p[2])
  # if(p[2]<=6):
  #   print(p)
  completedArray.append(p)
  matrix = copy.deepcopy(p[0])
  zeroAt = p[1].copy()
  wt = p[2]
  route = p[3]
  distTravelledUntilNow = p[4]
  if(calcDistFromAns(matrix, n) == 0):
    print("no of nodes visited: ",x)
    print(arr)
    print("route", route)
    break
  for die in move:
    if(checkInside(n, zeroAt[0] + die[0], zeroAt[1] + die[1])):
      newMatrix = copy.deepcopy(matrix)
      newMatrix[zeroAt[0]][zeroAt[1]] = newMatrix[zeroAt[0] + die[0]][zeroAt[1] + die[1]]
      newMatrix[zeroAt[0] + die[0]][zeroAt[1] + die[1]] = 0
      newNode = dict()
      newNode[0] = newMatrix
      newNode[1] = [zeroAt[0] + die[0], zeroAt[1] + die[1]]
      newNode[2] = calcDistFromAns(newMatrix, n)
      newNode[4] = distTravelledUntilNow + 1
      newRoute = route.copy()
      if(die[0]==1):
        newRoute.append('D')
        newNode[3] = newRoute
      elif(die[0]==-1):
        newRoute.append('U')
        newNode[3] = newRoute
      elif(die[1]==1):
        newRoute.append('R')
        newNode[3] = newRoute
      elif(die[1]==-1):
        newRoute.append('L')
        newNode[3] = newRoute
      if(checkIfNotVisisted(completedArray, newNode)):
        addNode(q, newNode)

{0: [[6, 5, 2], [3, 1, 7], [4, 8, 0]], 1: [2, 2], 2: 16, 3: [], 4: 0}
nodes visited: 0
nodes visited: 1
nodes visited: 2
nodes visited: 3
nodes visited: 4
nodes visited: 5
nodes visited: 6
nodes visited: 7
nodes visited: 8
nodes visited: 9
nodes visited: 10
nodes visited: 11
nodes visited: 12
nodes visited: 13
nodes visited: 14
nodes visited: 15
nodes visited: 16
nodes visited: 17
nodes visited: 18
nodes visited: 19
nodes visited: 20
nodes visited: 21
nodes visited: 22
nodes visited: 23
nodes visited: 24
nodes visited: 25
nodes visited: 26
nodes visited: 27
nodes visited: 28
nodes visited: 29
nodes visited: 30
nodes visited: 31
nodes visited: 32
nodes visited: 33
nodes visited: 34
nodes visited: 35
nodes visited: 36
nodes visited: 37
nodes visited: 38
nodes visited: 39
nodes visited: 40
nodes visited: 41
nodes visited: 42
nodes visited: 43
nodes visited: 44
nodes visited: 45
nodes visited: 46
nodes visited: 47
nodes visited: 48
nodes visited: 49
nodes visited: 50
nodes visited: 51
node

In [106]:
print(arr)

{0: [[6, 5, 2], [3, 1, 7], [4, 8, 0]], 1: [2, 2], 2: 16, 3: [], 4: 0}


In [107]:
import numpy as np
arr[0] = np.array(arr[0])
print(arr)
print(route)
matrix = arr[0]
zeroAt = arr[1]
for chr in route:
  print(matrix)
  if(chr == 'U'):
    matrix[zeroAt[0]][zeroAt[1]] = matrix[zeroAt[0] - 1][zeroAt[1]]
    matrix[zeroAt[0] - 1][zeroAt[1]] = 0
    zeroAt = [zeroAt[0] - 1, zeroAt[1]]
  if(chr == 'D'):
    matrix[zeroAt[0]][zeroAt[1]] = matrix[zeroAt[0] + 1][zeroAt[1]]
    matrix[zeroAt[0] + 1][zeroAt[1]] = 0
    zeroAt = [zeroAt[0] + 1, zeroAt[1]]
  if(chr == 'R'):
    matrix[zeroAt[0]][zeroAt[1]] = matrix[zeroAt[0]][zeroAt[1] + 1]
    matrix[zeroAt[0]][zeroAt[1] + 1] = 0
    zeroAt = [zeroAt[0], zeroAt[1] + 1]
  if(chr == 'L'):
    matrix[zeroAt[0]][zeroAt[1]] = matrix[zeroAt[0]][zeroAt[1] - 1]
    matrix[zeroAt[0]][zeroAt[1] - 1] = 0
    zeroAt = [zeroAt[0], zeroAt[1] - 1]
print(matrix)

{0: array([[6, 5, 2],
       [3, 1, 7],
       [4, 8, 0]]), 1: [2, 2], 2: 16, 3: [], 4: 0}
['U', 'L', 'U', 'R', 'D', 'L', 'L', 'D', 'R', 'R', 'U', 'L', 'U', 'R', 'D', 'D', 'L', 'L', 'U', 'U', 'R', 'D', 'L', 'D', 'R', 'R', 'U', 'L', 'D', 'R', 'U', 'L', 'D', 'L', 'U', 'R', 'R', 'D', 'L', 'U', 'L', 'D', 'R', 'R']
[[6 5 2]
 [3 1 7]
 [4 8 0]]
[[6 5 2]
 [3 1 0]
 [4 8 7]]
[[6 5 2]
 [3 0 1]
 [4 8 7]]
[[6 0 2]
 [3 5 1]
 [4 8 7]]
[[6 2 0]
 [3 5 1]
 [4 8 7]]
[[6 2 1]
 [3 5 0]
 [4 8 7]]
[[6 2 1]
 [3 0 5]
 [4 8 7]]
[[6 2 1]
 [0 3 5]
 [4 8 7]]
[[6 2 1]
 [4 3 5]
 [0 8 7]]
[[6 2 1]
 [4 3 5]
 [8 0 7]]
[[6 2 1]
 [4 3 5]
 [8 7 0]]
[[6 2 1]
 [4 3 0]
 [8 7 5]]
[[6 2 1]
 [4 0 3]
 [8 7 5]]
[[6 0 1]
 [4 2 3]
 [8 7 5]]
[[6 1 0]
 [4 2 3]
 [8 7 5]]
[[6 1 3]
 [4 2 0]
 [8 7 5]]
[[6 1 3]
 [4 2 5]
 [8 7 0]]
[[6 1 3]
 [4 2 5]
 [8 0 7]]
[[6 1 3]
 [4 2 5]
 [0 8 7]]
[[6 1 3]
 [0 2 5]
 [4 8 7]]
[[0 1 3]
 [6 2 5]
 [4 8 7]]
[[1 0 3]
 [6 2 5]
 [4 8 7]]
[[1 2 3]
 [6 0 5]
 [4 8 7]]
[[1 2 3]
 [0 6 5]
 [4 8 7]]
[[1 2 3]
 [4 6 5